// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"gauth.com/dbmanager"
	"github.com/joho/godotenv"
	"log"
	"os"
	"strconv"
)

// Injectors from wire.go:

func InitializeDB() dbmanager.DBContext {
	dbContext := NewDB()
	return dbContext
}

// wire.go:

func LoadFromEnv(key string) string {
	err := godotenv.Load()
	if err != nil {
		fmt.Println("Error loading .env file")
	}
	return os.Getenv(key)

}

func LoadDBVarsFromEnv() *dbmanager.DbSettingsConfig {
	fmt.Println("portNumber")
	portNumber, err := strconv.Atoi(LoadFromEnv("DBPort"))
	if err != nil {
		log.Fatalln(err)
	}
	return &dbmanager.DbSettingsConfig{
		Server:       LoadFromEnv("DBServer"),
		Port:         portNumber,
		User:         LoadFromEnv("DBUser"),
		Password:     LoadFromEnv("DBPassword"),
		DatabaseName: LoadFromEnv("DBName"),
	}
}

func NewDB() dbmanager.DBContext {
	conf := LoadDBVarsFromEnv()
	d := dbmanager.NewDBConnection(*conf)
	return dbmanager.DBContext{Ctx: d}
}
